### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ghost** [Sturmflut/ubuntu-touch-qt3d-cylinder#1]
Hello,

I am desperately searching an Ubuntu Touch app that doesn't depend on `qmlscene` and can be made cross-platform http://askubuntu.com/questions/829474 This app seems to met the requirement.

I can't compile it, it throws errors about not existing classes and methods. I tried to fix it but without success.

Can you please post an build instruction?

**Comment by Sturmflut** [comment]
I no longer own and Ubuntu Touch devices and the platform has changed considerably, so I#m very sorry, I can't help in this case.
